from time import sleep
import drawscore

drawscore.clear()
drawscore.score(1,1)
sleep(1)
drawscore.clear()
drawscore.score(2,2)
sleep(1)
drawscore.clear()
drawscore.score(3,3)
sleep(1)
drawscore.clear()
drawscore.score(4,4)
sleep(1)
drawscore.clear()
drawscore.score(5,5)
sleep(1)
drawscore.clear()
drawscore.score(6,6)
sleep(1)
drawscore.clear()
drawscore.score(7,7)
sleep(1)
drawscore.clear()
drawscore.score(8,8)
sleep(1)
drawscore.clear()
drawscore.score(9,9)
sleep(1)
drawscore.clear()
drawscore.score(9,10)
sleep(2)
drawscore.clear()
drawscore.score(10,9)
sleep(2)
drawscore.clear()
print()
